"""initial models

Revision ID: 61cf21ae4b83
Revises: 
Create Date: 2019-09-10 19:25:29.691832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cf21ae4b83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('should_escalate', sa.String(length=25), nullable=True),
    sa.Column('country_of_authentication1', sa.String(length=25), nullable=True),
    sa.Column('number_successful_logins1', sa.String(length=25), nullable=True),
    sa.Column('number_failed_logins1', sa.String(length=25), nullable=True),
    sa.Column('source_provider1', sa.String(length=50), nullable=True),
    sa.Column('country_of_authentication2', sa.String(length=25), nullable=True),
    sa.Column('number_successful_logins2', sa.String(length=25), nullable=True),
    sa.Column('number_failed_logins2', sa.String(length=25), nullable=True),
    sa.Column('source_provider2', sa.String(length=50), nullable=True),
    sa.Column('time_between_authentications', sa.String(length=25), nullable=True),
    sa.Column('vpn_confidence', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_clicked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('time_event_click', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('escalate', sa.String(length=15), nullable=True),
    sa.Column('confidence', sa.String(length=1), nullable=True),
    sa.Column('time_event_decision', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prequestionnaire_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('exp_researcher', sa.String(length=50), nullable=True),
    sa.Column('exp_admin', sa.String(length=50), nullable=True),
    sa.Column('exp_software', sa.String(length=50), nullable=True),
    sa.Column('exp_security', sa.String(length=50), nullable=True),
    sa.Column('familiarity_none', sa.Boolean(), nullable=True),
    sa.Column('familiarity_read', sa.Boolean(), nullable=True),
    sa.Column('familiarity_controlled', sa.Boolean(), nullable=True),
    sa.Column('familiarity_public', sa.Boolean(), nullable=True),
    sa.Column('familiarity_engineered', sa.Boolean(), nullable=True),
    sa.Column('subnet_mask', sa.String(length=256), nullable=True),
    sa.Column('network_address', sa.String(length=256), nullable=True),
    sa.Column('tcp_faster', sa.String(length=256), nullable=True),
    sa.Column('http_port', sa.String(length=256), nullable=True),
    sa.Column('firewall', sa.String(length=256), nullable=True),
    sa.Column('socket', sa.String(length=256), nullable=True),
    sa.Column('which_model', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('mental', sa.Float(precision=3), nullable=True),
    sa.Column('physical', sa.Float(precision=3), nullable=True),
    sa.Column('temporal', sa.Float(precision=3), nullable=True),
    sa.Column('performance', sa.Float(precision=3), nullable=True),
    sa.Column('effort', sa.Float(precision=3), nullable=True),
    sa.Column('frustration', sa.Float(precision=3), nullable=True),
    sa.Column('useful_info', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('should_escalate', sa.String(length=25), nullable=True),
    sa.Column('country_of_authentication1', sa.String(length=25), nullable=True),
    sa.Column('number_successful_logins1', sa.Integer(), nullable=True),
    sa.Column('number_failed_logins1', sa.Integer(), nullable=True),
    sa.Column('source_provider1', sa.String(length=50), nullable=True),
    sa.Column('country_of_authentication2', sa.String(length=25), nullable=True),
    sa.Column('number_successful_logins2', sa.Integer(), nullable=True),
    sa.Column('number_failed_logins2', sa.Integer(), nullable=True),
    sa.Column('source_provider2', sa.String(length=50), nullable=True),
    sa.Column('time_between_authentications', sa.Float(), nullable=True),
    sa.Column('vpn_confidence', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_event_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('escalate', sa.String(length=15), nullable=True),
    sa.Column('confidence', sa.String(length=1), nullable=True),
    sa.Column('time_event_decision', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('events', sa.String(length=256), nullable=True),
    sa.Column('questionnaire_complete', sa.Boolean(), nullable=True),
    sa.Column('training_complete', sa.Boolean(), nullable=True),
    sa.Column('experiment_complete', sa.Boolean(), nullable=True),
    sa.Column('survey_complete', sa.Boolean(), nullable=True),
    sa.Column('completion_code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('training_event_decision')
    op.drop_table('training_event')
    op.drop_table('survey_answers')
    op.drop_table('prequestionnaire_answers')
    op.drop_table('event_decision')
    op.drop_table('event_clicked')
    op.drop_table('event')
    # ### end Alembic commands ###
